---
abstract: 'Simple utility to get canonical paths.'
author:
  - 'mattn <mattn.jp@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Path-Canonical
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Path::Canonical:
    file: lib/Path/Canonical.pm
    version: '0.05'
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/mattn/p5-Path-Canonical/issues
  homepage: https://github.com/mattn/p5-Path-Canonical
  repository: git://github.com/mattn/p5-Path-Canonical.git
version: '0.05'
x_authority: cpan:MATTN
x_contributors:
  - 'lestrrat <lestrrat+github@gmail.com>'
